In [8]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 120)
print('pandas', pd.__version__, '| numpy', np.__version__)

pandas 2.2.3 | numpy 2.1.3

In [9]:
import os
FILE = 'kunjungan_perpustakaan_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih penjualan_umkm_2024.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')
print('Siap:', os.path.exists(FILE))

Saving kunjungan_perpustakaan_2025.csv to kunjungan_perpustakaan_2025.csv
Siap: True

---
## Bagian A — Memuat dan memeriksa data (Latihan 1)
**Tujuan:** sebelum menganalisis apa pun, jawab empat pertanyaan: *berapa besar data ini, apa saja kolomnya, apa tipe datanya, dan seberapa bersih?*

In [10]:
# DEMO A1 — memuat data
df = pd.read_csv('kunjungan_perpustakaan_2025.csv')
df.head()

  id_kunjungan     tanggal nim_hash               prodi  angkatan  durasi_menit  jumlah_pinjam   jenis_ruang  kepuasan
0      K100000  2025-05-18    H1160    Sistem Informasi      2024            30              0  Lab Komputer       5.0
1      K100001  2025-02-22    H1190  Teknik Informatika      2023            78              1    Ruang Baca       3.6
2      K100002  2025-06-11    H1070    Sistem Informasi      2025            56              2    Ruang Baca       4.1
3      K100003  2025-05-06    H1001    Sistem Informasi      2024            12              1  Lab Komputer       2.6
4      K100004  2025-02-24    H1047  Teknik Informatika      2023            67              1  Lab Komputer       4.3

In [5]:
# DEMO A2 — ukuran dan struktur
print('Baris, kolom:', df.shape)
df.info()

Baris, kolom: (900, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_kunjungan   900 non-null    object
 1   tanggal        900 non-null    object
 2   nim_hash       900 non-null    object
 3   prodi          900 non-null    object
 4   angkatan       900 non-null    int64
 5   durasi_menit   900 non-null    int64
 6   jumlah_pinjam  900 non-null    int64
 7   jenis_ruang    900 non-null    object
 8   kepuasan       855 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 63.4+ KB

In [6]:
# DEMO A3 — ringkasan numerik
df.describe()

          angkatan  durasi_menit  jumlah_pinjam    kepuasan
count   900.000000    900.000000     900.000000  855.000000
mean   2023.472222     74.911111       1.103333    3.981170
std       1.023802     34.143694       1.043754    0.645001
min    2022.000000      5.000000       0.000000    1.500000
25%    2023.000000     51.000000       0.000000    3.600000
50%    2023.500000     73.000000       1.000000    4.000000
75%    2024.000000     98.000000       2.000000    4.500000
max    2025.000000    184.000000       6.000000    5.000000

> **Catatan dosen:** `describe()` secara default hanya meringkas kolom numerik. Coba `df.describe(include='object')` untuk kolom teks.

In [7]:
# a. Tampilkan 5 baris TERAKHIR dari df
print(df.tail())

# b. Tampilkan daftar nama kolom beserta tipe datanya
print(df.dtypes)

    id_kunjungan     tanggal nim_hash               prodi  angkatan  durasi_menit  jumlah_pinjam    jenis_ruang  \
895      K100895  2025-06-23    H1133  Teknik Informatika      2022             7              1     Ruang Baca
896      K100896  2025-03-19    H1117  Teknik Informatika      2025            82              0  Ruang Diskusi
897      K100897  2025-06-26    H1052  Teknik Informatika      2023            41              1     Ruang Baca
898      K100898  2025-06-13    H1021  Teknik Informatika      2023             5              0  Ruang Diskusi
899      K100899  2025-06-18    H1070    Sistem Informasi      2025            65              1     Ruang Baca

     kepuasan
895       3.1
896       3.1
897       NaN
898       3.6
899       3.8
id_kunjungan      object
tanggal           object
nim_hash          object
prodi             object
angkatan           int64
durasi_menit       int64
jumlah_pinjam      int64
jenis_ruang       object
kepuasan         float64
dtype: object

In [10]:
# a. Hitung jumlah nilai kosong (missing) per kolom
print("Missing value per kolom:")
print(df.isnull().sum())

# b. Hitung jumlah baris duplikat
print("\nJumlah baris duplikat:", df.duplicated().sum())

# c. Hitung berapa nilai unik pada kolom 'prodi'
print("\nJumlah nilai unik kolom prodi:", df['prodi'].nunique())

Missing value per kolom:
id_kunjungan      0
tanggal           0
nim_hash          0
prodi             0
angkatan          0
durasi_menit      0
jumlah_pinjam     0
jenis_ruang       0
kepuasan         45
dtype: int64

Jumlah baris duplikat: 0

Jumlah nilai unik kolom prodi: 3

**Diskusi (2 menit):** mengapa jumlah nilai unik `kota` lebih banyak daripada jumlah kota sebenarnya? Masalah seperti ini akan kita tangani secara sistematis pada pertemuan 4–5.

---
## Bagian B — Seleksi dan filter (Latihan 2, berpasangan)
**Tujuan:** mengambil bagian data yang relevan dengan pertanyaan analisis.

In [12]:
# DEMO B1 — memilih kolom

# Satu kolom -> Series
df['durasi_menit'].head()

# Beberapa kolom -> DataFrame
df[['id_kunjungan', 'prodi', 'durasi_menit']].head()

  id_kunjungan               prodi  durasi_menit
0      K100000    Sistem Informasi            30
1      K100001  Teknik Informatika            78
2      K100002    Sistem Informasi            56
3      K100003    Sistem Informasi            12
4      K100004  Teknik Informatika            67

In [15]:
# DEMO B2 — loc (berbasis label) vs iloc (berbasis posisi)

# loc: mengambil berdasarkan nama kolom
print(df.loc[0, 'prodi'])

# iloc: mengambil berdasarkan posisi kolom
# kolom ke-4 adalah angkatan
print(df.iloc[0, 4])

# loc: mengambil baris 0 sampai 4 dan beberapa kolom
df.loc[0:4, ['id_kunjungan', 'prodi', 'durasi_menit']]

Sistem Informasi
2024

  id_kunjungan               prodi  durasi_menit
0      K100000    Sistem Informasi            30
1      K100001  Teknik Informatika            78
2      K100002    Sistem Informasi            56
3      K100003    Sistem Informasi            12
4      K100004  Teknik Informatika            67

In [17]:
# DEMO B3 — filter dengan kondisi (boolean mask)

mask = df['durasi_menit'] > 60

print('Kunjungan dengan durasi di atas 60 menit:', mask.sum())

df[mask].head()

Kunjungan dengan durasi di atas 60 menit: 598

,id_kunjungan,tanggal,nim_hash,prodi,angkatan,durasi_menit,jumlah_pinjam,jenis_ruang,kepuasan
1,K100001,2025-02-22,H1190,Teknik Informatika,2023,78,1,Ruang Baca,3.6
4,K100004,2025-02-24,H1047,Teknik Informatika,2023,67,1,Lab Komputer,4.3
5,K100005,2025-04-07,H1063,Teknik Informatika,2024,67,1,Ruang Diskusi,3.5
7,K100007,2025-06-29,H1050,Teknik Informatika,2024,78,0,Ruang Baca,3.9
9,K100009,2025-05-14,H1170,Teknik Informatika,2025,83,2,Ruang Baca,4.1

In [18]:
# DEMO B4 — menggabungkan kondisi

# Kunjungan dengan durasi > 60 menit DAN jumlah pinjaman >= 2
hi = df[
    (df['durasi_menit'] > 60) &
    (df['jumlah_pinjam'] >= 2)
]

print('Durasi > 60 menit dan jumlah pinjam >= 2:', hi.shape)

# Kunjungan yang menggunakan Ruang Baca atau Ruang Diskusi
ruang = df[
    df['jenis_ruang'].isin(['Ruang Baca', 'Ruang Diskusi'])
]

print('Kunjungan di Ruang Baca atau Ruang Diskusi:', ruang.shape)

Durasi > 60 menit dan jumlah pinjam >= 2: (173, 9)
Kunjungan di Ruang Baca atau Ruang Diskusi: (716, 9)

In [19]:
# TODO B5 — Data kunjungan dengan kepuasan rendah

# a. Ambil semua kunjungan dengan kepuasan < 3
kepuasan_rendah = df[df['kepuasan'] < 3]

print("Kunjungan dengan kepuasan < 3:")
print(kepuasan_rendah)

# b. Jumlah kunjungan dan rata-rata durasi
print("\nJumlah kunjungan:", len(kepuasan_rendah))
print("Rata-rata durasi:", kepuasan_rendah['durasi_menit'].mean())

# c. Ambil kunjungan dengan jumlah pinjam >= 2
pinjam_banyak = df[df['jumlah_pinjam'] >= 2]

print("\nKunjungan dengan jumlah pinjam >= 2:")
print(pinjam_banyak)

Kunjungan dengan kepuasan < 3:
    id_kunjungan     tanggal nim_hash               prodi  angkatan  durasi_menit  jumlah_pinjam    jenis_ruang  \
3        K100003  2025-05-06    H1001    Sistem Informasi      2024            12              1   Lab Komputer
20       K100020  2025-02-06    H1138  Teknik Informatika      2022            62              1   Lab Komputer
32       K100032  2025-05-29    H1104  Teknik Informatika      2024            57              2  Ruang Diskusi
60       K100060  2025-04-01    H1058  Teknik Informatika      2022            70              1     Ruang Baca
75       K100075  2025-03-24    H1009  Teknik Informatika      2025           108              1     Ruang Baca
79       K100079  2025-06-28    H1127    Sistem Informasi      2023            82              1     Ruang Baca
82       K100082  2025-03-09    H1178    Sistem Informasi      2025            91              0   Lab Komputer
91       K100091  2025-04-26    H1153  Teknik Informatika      2025            87              0  Ruang Diskusi
95       K100095  2025-03-15    H1175  Teknik Informatika      2024            89              1  Ruang Diskusi
119      K100119  2025-02-05    H1078  Teknik Informatika      2024            56              2   Lab Komputer
130      K100130  2025-04-07    H1149    Sistem Informasi      2024           128              2  Ruang Diskusi
163      K100163  2025-02-06    H1108      Bisnis Digital      2024           108              1     Ruang Baca
170      K100170  2025-03-07    H1003  Teknik Informatika      2024            76              3     Ruang Baca
175      K100175  2025-06-28    H1125  Teknik Informatika      2022           113              1     Ruang Baca
199      K100199  2025-06-11    H1197    Sistem Informasi      2023           135              1     Ruang Baca
205      K100205  2025-04-21    H1141  Teknik Informatika      2023            77              0     Ruang Baca
208      K100208  2025-04-03    H1020  Teknik Informatika      2023            94              0  Ruang Diskusi
214      K100214  2025-06-11    H1086  Teknik Informatika      2024             5              2  Ruang Diskusi
215      K100215  2025-04-15    H1180  Teknik Informatika      2024            55              1     Ruang Baca
224      K100224  2025-03-01    H1084  Teknik Informatika      2025           106              1  Ruang Diskusi
233      K100233  2025-05-05    H1019      Bisnis Digital      2022            90              0     Ruang Baca
248      K100248  2025-04-04    H1191  Teknik Informatika      2022            57              1   Lab Komputer
249      K100249  2025-04-28    H1060  Teknik Informatika      2022            67              4     Ruang Baca
252      K100252  2025-03-29    H1034  Teknik Informatika      2023            55              2     Ruang Baca
267      K100267  2025-03-19    H1144      Bisnis Digital      2025            92              0  Ruang Diskusi
307      K100307  2025-03-20    H1140    Sistem Informasi      2024            45              4  Ruang Diskusi
373      K100373  2025-05-28    H1100    Sistem Informasi      2023            97              1     Ruang Baca
375      K100375  2025-05-12    H1032    Sistem Informasi      2024            51              2     Ruang Baca
386      K100386  2025-02-15    H1199  Teknik Informatika      2024            32              1   Lab Komputer
443      K100443  2025-04-07    H1112    Sistem Informasi      2023            71              0     Ruang Baca
457      K100457  2025-03-23    H1098    Sistem Informasi      2022            35              0     Ruang Baca
475      K100475  2025-06-30    H1189    Sistem Informasi      2022            60              2     Ruang Baca
477      K100477  2025-02-25    H1142    Sistem Informasi      2025            83              1   Lab Komputer
502      K100502  2025-04-20    H1126      Bisnis Digital      2023            92              1  Ruang Diskusi
566      K100566  2025-04-04    H1026      Bisnis Digital      2023            73              0     Ruang Baca
595      K100595  2025-06-08    H1097  Teknik Informatika      2024            22              0     Ruang Baca
613      K100613  2025-02-16    H1001    Sistem Informasi      2024            60              0   Lab Komputer
615      K100615  2025-02-25    H1063  Teknik Informatika      2022            95              1  Ruang Diskusi
636      K100636  2025-03-03    H1043  Teknik Informatika      2022            83              0  Ruang Diskusi
640      K100640  2025-04-24    H1110    Sistem Informasi      2022            97              3     Ruang Baca
668      K100668  2025-03-29    H1168    Sistem Informasi      2023           110              0     Ruang Baca
685      K100685  2025-03-15    H1067  Teknik Informatika      2025           130              2  Ruang Diskusi
714      K100714  2025-06-26    H1106  Teknik Informatika      2023           102              2     Ruang Baca
718      K100718  2025-05-19    H1010    Sistem Informasi      2022           116              1  Ruang Diskusi
721      K100721  2025-02-17    H1080      Bisnis Digital      2024            60              1  Ruang Diskusi
737      K100737  2025-04-19    H1191  Teknik Informatika      2025           105              0     Ruang Baca
743      K100743  2025-02-02    H1122  Teknik Informatika      2023            88              1   Lab Komputer
764      K100764  2025-05-05    H1011      Bisnis Digital      2024            70              3  Ruang Diskusi
771      K100771  2025-02-10    H1186  Teknik Informatika      2022             5              2   Lab Komputer
784      K100784  2025-06-18    H1036  Teknik Informatika      2024            82              0  Ruang Diskusi
792      K100792  2025-04-08    H1088      Bisnis Digital      2023           123              4     Ruang Baca
826      K100826  2025-02-25    H1007    Sistem Informasi      2025           116              0     Ruang Baca
832      K100832  2025-06-07    H1011  Teknik Informatika      2024            23              2  Ruang Diskusi
840      K100840  2025-06-19    H1119  Teknik Informatika      2024            82              0     Ruang Baca
876      K100876  2025-03-15    H1136  Teknik Informatika      2024            79              2  Ruang Diskusi

     kepuasan
3         2.6
20        2.7
32        1.5
60        2.8
75        2.8
79        2.4
82        2.8
91        2.8
95        2.6
119       2.7
130       2.9
163       2.8
170       2.8
175       2.2
199       2.8
205       2.8
208       2.9
214       2.9
215       2.8
224       2.8
233       2.9
248       2.7
249       2.7
252       2.9
267       2.9
307       2.3
373       2.6
375       2.5
386       2.8
443       2.7
457       2.7
475       2.7
477       2.8
502       2.3
566       2.5
595       2.9
613       2.9
615       2.9
636       2.8
640       2.8
668       2.7
685       2.5
714       2.8
718       2.4
721       2.5
737       2.6
743       2.4
764       2.8
771       2.9
784       2.9
792       2.8
826       2.8
832       2.8
840       2.6
876       2.5

Jumlah kunjungan: 55
Rata-rata durasi: 77.43636363636364

Kunjungan dengan jumlah pinjam >= 2:
    id_kunjungan     tanggal nim_hash               prodi  angkatan  durasi_menit  jumlah_pinjam    jenis_ruang  \
2        K100002  2025-06-11    H1070    Sistem Informasi      2025            56              2     Ruang Baca
8        K100008  2025-02-24    H1076    Sistem Informasi      2022            42              2  Ruang Diskusi
9        K100009  2025-05-14    H1170  Teknik Informatika      2025            83              2     Ruang Baca
13       K100013  2025-06-23    H1168    Sistem Informasi      2023            86              2  Ruang Diskusi
14       K100014  2025-04-05    H1058    Sistem Informasi      2025           100              2     Ruang Baca
..           ...         ...      ...                 ...       ...           ...            ...            ...
880      K100880  2025-06-05    H1055      Bisnis Digital      2023            84              3     Ruang Baca
885      K100885  2025-02-10    H1110    Sistem Informasi      2023            73              2   Lab Komputer
888      K100888  2025-02-03    H1067      Bisnis Digital      2023            47              3     Ruang Baca
889      K100889  2025-03-22    H1014  Teknik Informatika      2022            93              2   Lab Komputer
893      K100893  2025-03-20    H1162    Sistem Informasi      2024           126              2  Ruang Diskusi

     kepuasan
2         4.1
8         4.7
9         4.1
13        3.6
14        4.4
..        ...
880       3.6
885       4.0
888       4.6
889       5.0
893       3.9

[269 rows x 9 columns]

In [21]:
# TODO B6 — pertanyaan bisnis

# Tampilkan 10 kunjungan dengan durasi paling lama
# dengan jumlah pinjaman minimal 1

hasil_b6 = df[df['jumlah_pinjam'] >= 1]

hasil_b6 = hasil_b6.sort_values(
    'durasi_menit',
    ascending=False
)

print("10 kunjungan dengan durasi paling lama:")
print(
    hasil_b6[
        ['id_kunjungan', 'prodi', 'durasi_menit',
         'jumlah_pinjam', 'jenis_ruang', 'kepuasan']
    ].head(10)
)

10 kunjungan dengan durasi paling lama:
    id_kunjungan               prodi  durasi_menit  jumlah_pinjam    jenis_ruang  kepuasan
283      K100283      Bisnis Digital           184              1     Ruang Baca       5.0
749      K100749  Teknik Informatika           169              1  Ruang Diskusi       3.7
589      K100589      Bisnis Digital           158              4   Lab Komputer       3.4
171      K100171  Teknik Informatika           156              1   Lab Komputer       4.0
548      K100548    Sistem Informasi           155              2     Ruang Baca       4.7
218      K100218      Bisnis Digital           155              1     Ruang Baca       3.4
219      K100219    Sistem Informasi           153              2   Lab Komputer       3.7
808      K100808  Teknik Informatika           152              1  Ruang Diskusi       3.8
315      K100315    Sistem Informasi           152              1     Ruang Baca       3.8
470      K100470  Teknik Informatika           147              2  Ruang Diskusi       4.2

---
## Bagian C — Kolom turunan dan pengurutan

In [ ]:
# DEMO C1 — membuat kolom baru

# Membuat kolom kategori durasi
df['kategori_durasi'] = np.where(
    df['durasi_menit'] > 60,
    'Lama',
    'Singkat'
)

df[['durasi_menit', 'kategori_durasi']].head()

In [ ]:
# DEMO C2 — kolom tanggal

df['tanggal'] = pd.to_datetime(df['tanggal'])

df['bulan'] = df['tanggal'].dt.month

df['nama_hari'] = df['tanggal'].dt.day_name()

df[['tanggal', 'bulan', 'nama_hari']].head()

In [ ]:
# TODO C3

# a. Buat kolom kelas_durasi
# Lama jika durasi > 60 menit, selain itu Singkat
df['kelas_durasi'] = np.where(
    df['durasi_menit'] > 60,
    'Lama',
    'Singkat'
)

# b. Hitung jumlah tiap kelas
print("Jumlah berdasarkan kelas durasi:")
print(df['kelas_durasi'].value_counts())

# c. Tampilkan 5 kunjungan dengan durasi terbesar
print("\n5 kunjungan dengan durasi terbesar:")

print(
    df.sort_values(
        'durasi_menit',
        ascending=False
    )[
        ['id_kunjungan', 'prodi', 'durasi_menit',
         'jumlah_pinjam', 'jenis_ruang']
    ].head(5)
)

---
## Bagian D — Agregasi dengan groupby
Pola yang akan Anda pakai sepanjang semester: **split → apply → combine**.

In [ ]:
# DEMO D1 — agregasi sederhana

df.groupby('prodi')['durasi_menit'].mean().round(2)

In [ ]:
# DEMO D2 — beberapa agregasi sekaligus

ringkas = (
    df.groupby('prodi')
      .agg(
          jumlah_kunjungan=('id_kunjungan', 'count'),
          rata_rata_durasi=('durasi_menit', 'mean'),
          rata_rata_pinjam=('jumlah_pinjam', 'mean'),
          rata_rata_kepuasan=('kepuasan', 'mean')
      )
      .round(2)
      .sort_values('jumlah_kunjungan', ascending=False)
)

ringkas

In [23]:
# DEMO D3 — dua kunci pengelompokan

df.groupby(
    ['prodi', 'jenis_ruang']
)['durasi_menit'].mean().unstack(fill_value=0)

jenis_ruang         Lab Komputer  Ruang Baca  Ruang Diskusi
prodi
Bisnis Digital         81.638889   78.000000      72.269231
Sistem Informasi       69.396552   78.465116      72.096774
Teknik Informatika     72.588889   76.048309      73.578313

In [24]:
# c. Jumlah kunjungan per bulan

# Pastikan kolom tanggal menjadi datetime
df['tanggal'] = pd.to_datetime(df['tanggal'])

kunjungan_bulan = (
    df.groupby(df['tanggal'].dt.month)
      .size()
      .sort_values(ascending=False)
)

print("\nJumlah kunjungan per bulan:")
print(kunjungan_bulan)

Jumlah kunjungan per bulan:
tanggal
4    190
5    186
6    180
3    177
2    167
dtype: int64

In [ ]:
# TODO D5 — satu temuan
# Tulis SATU kalimat temuan dari hasil di atas dalam sel Markdown berikutnya.
# Format: 'X memiliki ... sebesar ..., lebih tinggi/rendah dibandingkan ...'
# Ingat: ini temuan DESKRIPTIF, belum boleh diklaim sebagai sebab-akibat.

**Temuan saya:** Teknik Informatika memiliki rata-rata kepuasan terendah sebesar 3,95, lebih rendah dibandingkan Bisnis Digital sebesar 4,04.

---
## Bagian E — Menyimpan hasil dan mengunggah ke repositori tim

In [ ]:
# DEMO E1 — menyimpan hasil agregasi
ringkas.to_csv('ringkasan_kategori.csv')
print('Tersimpan.')
# Di Colab: files.download('ringkasan_kategori.csv') untuk mengunduh

### Alur kerja repositori tim (dilakukan bersama di kelas)
```
nama-tim-eda/
├── README.md              <- tujuan proyek, anggota, cara menjalankan
├── requirements.txt
├── data/
│   ├── raw/               <- data asli, TIDAK PERNAH diubah
│   └── processed/         <- hasil olahan
├── notebooks/             <- 01_quality.ipynb, 02_cleaning.ipynb, ...
├── knime/
└── reports/
```
**Dua cara menyimpan notebook ke GitHub:**
1. Colab → *File → Save a copy in GitHub* → pilih repo tim → tulis pesan commit.
2. Melalui terminal/Git lokal:
```bash
git clone https://github.com/<organisasi-tim>/<nama-repo>.git
cd <nama-repo>
git checkout -b latihan-pert2
git add notebooks/P02_praktikum.ipynb
git commit -m 'Latihan pert 2: eksplorasi awal data penjualan UMKM'
git push origin latihan-pert2
```
**Aturan pesan commit di kelas ini:** kalimat perintah, maksimal ±60 karakter, menjelaskan *apa* dan *mengapa*.
Contoh baik: `Tambah agregasi penjualan per kota`. Contoh buruk: `update`, `fix`, `asdf`.

In [ ]:
# TODO E2 — checklist sebelum commit
# 1. Restart runtime lalu Run all -> pastikan tidak ada error
# 2. Hapus sel percobaan yang tidak terpakai
# 3. Pastikan nama file mengikuti pola: P02_praktikum_<nama>.ipynb
# 4. Commit & push, lalu salin tautan commit Anda ke LMS

---
## Bagian F — Checkpoint proyek (dikerjakan bersama tim, di luar kelas)
Terapkan Bagian A pada **dataset calon proyek tim Anda**, lalu jawab di README repositori:
1. Berapa baris dan kolom? Apa satuan tiap barisnya (satu baris = satu apa)?
2. Kolom mana yang numerik, kategorikal, dan tanggal?
3. Kolom mana yang bermasalah (kosong, tipe salah, nilai tidak konsisten)?
4. Apakah data ini cukup untuk menjawab pertanyaan analisis tim? Jika belum, apa yang kurang?

Hasil poin 1–4 menjadi bahan **M1 (proposal proyek)** yang dikumpulkan pada pertemuan 3.